repos:
  - repo: local
    hooks:
      - id: lint
        language: system
        name: lint
        entry: bash -c "poetry run ruff check ."
      - id: type-check
        language: system
        name: type-check
        entry: bash -c "poetry run mypy ."
      - id: test
        language: system
        name: test
        entry: bash -c "poetry run pytest"
